name: flutter_web_browser
description: A flutter plugin project to open a web page with Chrome Custom Tabs & SFSafariViewController.
author: Victor Bonnet<victor.bonnet@gmail.com>
homepage: https://github.com/victorbonnet/flutter_web_browser

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.vbonnet.flutterwebbrowser
        pluginClass: FlutterWebBrowserPlugin
      ios:
        pluginClass: FlutterWebBrowserPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.16.0 <2.0.0"
